name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ amd64 ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      
      - name: Build for ${{ matrix.goos }} ${{ matrix.goarch }}
        run: |
          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o sops-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
      
      - name: Upload artifact ${{ matrix.goos }}-${{ matrix.goarch }}
        uses: actions/upload-artifact@v2
        with:
          name: sops-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: sops-*
  
  prepare_release:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
  
  release:
    needs: [ build, prepare_release ]
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ amd64 ]
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: sops-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: sops-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_content_type: application/octet-stream
